export  interface Phone{
  id :number,
  name_phone: String,
  title : String,
  description : String,
  price : number,
  quantity : number,
  size : String,
  weight : String,
  color : String,
  image : String,
  memory : String,
  os : string,
  cpu_speed : String,
  camera_primary : String,
  battery : String,
  warranty : String,
  bluetooth : String,
  wlan : String,
  promotion_price : number,
  start_promotion : String,
  end_promotion : String,
}
